_target_: transformix.TransformixPMLM

lr: 1e-3
# model_name: facebook/esm2_t6_8M_UR50D
model_name: MLM_24M
mask_percentage: 0.25
ckpt_path: null
num_warmup_steps: 10_000
# tokenizer_dir: null
tokenizer_dir: aa_tokenizer
max_length: 512
num_training_steps: 50_000
